# Generated by Django 5.2.1 on 2025-05-23 12:20

import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='about_images/')),
                ('image2', models.ImageField(upload_to='about_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
            ],
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('working_days', multiselectfield.db.fields.MultiSelectField(choices=[('пн', 'пн'), ('вт', 'вт'), ('ср', 'ср'), ('чт', 'чт'), ('пт', 'пт'), ('сб', 'сб'), ('вс', 'вс')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('about_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.about')),
            ],
            bases=('restaurant.about',),
        ),
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('about_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.about')),
            ],
            bases=('restaurant.about',),
        ),
        migrations.CreateModel(
            name='ColdDrink',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.CreateModel(
            name='EasternCuisine',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.CreateModel(
            name='HotDrink',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.CreateModel(
            name='NationalFood',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.meal')),
            ],
            bases=('restaurant.meal',),
        ),
        migrations.AddField(
            model_name='meal',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.mealimage'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.image')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='supplements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.supplement'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.supplementitem'),
        ),
    ]
