# Generated by Django 5.2.1 on 2025-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='day_en',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='day_ky',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='day_ru',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='Ingredient',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
