# Generated by Django 5.2.1 on 2025-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient_ru',
            field=models.TextField(null=True),
        ),
    ]
