# Generated by Django 5.2.1 on 2025-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='supplementitem',
            name='item_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplementitem',
            name='item_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplementitem',
            name='item_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
