# Generated by Django 5.2.1 on 2025-05-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_about_description_en_about_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='supplements',
        ),
        migrations.AddField(
            model_name='supplementitem',
            name='supplements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.supplement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplement',
            name='supplement_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal'),
        ),
    ]
