# Generated by Django 5.2.1 on 2025-05-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_ingredient_meal_ingredient_meal_ingredient_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('label_ky', models.CharField(max_length=32, null=True)),
                ('label_en', models.CharField(max_length=32, null=True)),
                ('label_ru', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=64)),
                ('title_ky', models.CharField(max_length=64, null=True)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='label',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='label_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='label_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='label_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='label',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='label_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='label_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='label_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='title_address',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='title_address_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_address_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_address_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_phone',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='title_phone_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_phone_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_phone_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='label',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='label_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='label_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='label_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_contact',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_contact_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_contact_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_contact_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
            preserve_default=False,
        ),
    ]
