# Generated by Django 5.2.1 on 2025-05-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_meal_supplements_supplementitem_supplements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='schedule',
        ),
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantinfo'),
            preserve_default=False,
        ),
    ]
