# Generated by Django 5.2.1 on 2025-05-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_aboutus_label_aboutus_label_en_aboutus_label_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='image2',
        ),
        migrations.CreateModel(
            name='BestSellerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='best_seller_images/')),
                ('best_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.bestseller')),
            ],
        ),
    ]
