# Generated by Django 5.2.1 on 2025-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurantimage_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(default=1, upload_to='main_page_image/'),
            preserve_default=False,
        ),
    ]
