# Generated by Django 5.2.1 on 2025-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_bestseller_image1_remove_bestseller_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_region',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_schedule',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
