# Generated by Django 5.2.1 on 2025-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='about_ptr',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='about_ptr',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(default=1, upload_to='about_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(default=1, upload_to='about_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='image1',
            field=models.ImageField(default=1, upload_to='about_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='image2',
            field=models.ImageField(default=1, upload_to='about_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
