# Generated by Django 5.2.1 on 2025-05-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantinfo_title_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_region_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_region_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_region_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_schedule_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_schedule_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_schedule_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
