# Generated by Django 5.2.1 on 2025-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_aboutus_about_ptr_remove_bestseller_about_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantimage',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
