# Generated by Django 5.2.1 on 2025-05-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurantinfo_title_region_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellerimage',
            name='best_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_photos', to='restaurant.bestseller'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='restaurant.meal'),
        ),
        migrations.AlterField(
            model_name='supplementitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='supplementitem',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.supplement'),
        ),
    ]
