# Generated by Django 5.2.1 on 2025-05-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_bestsellerimage_best_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
