# Generated by Django 5.2.1 on 2025-05-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurant.restaurantimage'),
        ),
        migrations.AlterField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_images', to='restaurant.meal'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='restaurant.restaurantinfo'),
        ),
    ]
