# Generated by Django 5.2.1 on 2025-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_contact_phone_alter_image_restaurant_and_more'),
        ('restaurant', '0010_alter_image_restaurant_alter_mealimage_meal_and_more'),
    ]

    operations = [
    ]
